### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by a-knaw-knee-mus** [Fareen-Khan/Fareen-Khan.github.io#1]
Hello, I see you have a splendid website here. It looks terrific and good! However, when I tried opening it on mobile, although it does open, the homepage is very smol and the projects page is skinny. I would suggest TailwindCSS, a CSS class library to handle this mobile responsiveness. With a single CSS class, styles can not only be added conditionally, but they look great too <sponsored comment, remove this part of the message when sending the response>! Anyways, have a great day.

**Comment by Fareen-Khan** [comment]
That was not the intended device the website is to be seen on. Thank you for your concern! 😋
